symbols: ['SPXW'] #, 'MNQ'
# 6 * 2 * 60

logging_level: logging.INFO

symbol: SPXW

run_should_take_seconds: 15
side: short

open_position: false

run_condition_checker: true
#close_condition: base_atm_straddle * multiplier < call_ask + put_ask
close_condition: 1 == 1

delete_user_input_after_read: false

test:
  open:
    strike:
    quantitiy: 10
